name: "{main} on Push Workflow"

on:
  push:
    branches: [main]
  #workflow_dispatch:

env:
  PRISMA_API_URL: ${{ vars.PRISMA_API_URL }}
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  IMAGE_PATH: "."
  TF_CLOUD_ORGANIZATION: "${{ vars.TERRAFORM_CLOUD_ORG }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "${{ vars.TERRAFORM_CLOUD_WORKSPACE }}"
  TF_CONFIG_DIRECTORY: "./terraform/"


jobs:
  #From checkov_iac_sca_scan.yml
  checkov_iac_sca_scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    runs-on: ubuntu-latest
    name: "Checkov IAC and SCA Scan on Push"
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Run Checkov Action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: '.'
          soft_fail: true
          api-key: ${{ secrets.BC_API_KEY }}
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif
          
#from twistcli_image_scan.yml
  twistcli_image_scan:
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    
    name: Build and scan image
    runs-on: ubuntu-latest
    needs: checkov_iac_sca_scan

    steps:
      - name: Check out the repository
        uses: actions/checkout@master

      - name: Build the Image
        run: docker build -t ${{ env.IMAGE_NAME }} ${{ env.IMAGE_PATH }}
        
      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.IMAGE_NAME }}
          #containerized: true
          
      # (Optional) for compatibility with GitHub's code scanning alerts
      - name: Upload SARIF file
        if: ${{ always() }} # necessary if using failure thresholds in the image scan
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}

#from push_image_to_aws_ecr.yml
  build_and_push_image:
      
      name: "Build and Push Image"
      runs-on: ubuntu-latest
      needs: [ checkov_iac_sca_scan, twistcli_image_scan]

      steps:
        - name: Set current date as env variable
          run: echo "DATE=$(date +'%Y%m%d_%H%M')" >> $GITHUB_ENV
    
        - name: Check out code
          uses: actions/checkout@master
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@master
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{vars.AWS_ECR_REPOSITORY}}
            IMAGE_TAG: image_${{ github.event.repository.name }}_${{ env.DATE }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  #from terraform_apply.yml
  terraform_apply:
      name: "Terraform Apply"
      runs-on: ubuntu-latest
      needs: [ checkov_iac_sca_scan, twistcli_image_scan, build_and_push_image]

      permissions:
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
          id: upload-config
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.TF_CONFIG_DIRECTORY }}

        - name: Create Run
          uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
          id: create-run
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            configuration_version: ${{ steps.upload-config.outputs.configuration_version_id }}

        - name: Apply Run
          uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.4
          if: fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable
          id: apply-run
          with:
            run: ${{ steps.create-run.outputs.run_id }}
            comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"            
