name: "IaC Yor Tagging on Push"

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  yor-tagging-job:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    name: Yor Tagging of IaC Templates
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: yor-tagging
        uses: bridgecrewio/yor-action@main
        env:
          LOG_LEVEL: WARNING
        with:
          tags: git_file,git_commit,git_repository,yor_trace
          tag_prefix: "secure_"
