name: "IaC Yor Tagging on Push"

on:

  workflow_dispatch:


jobs:
  yor-tagging-job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: yor-tagging
        uses: bridgecrewio/yor-action@main
        env:
          LOG_LEVEL: DEBUG
        #with:
        #  tags: git_file,git_commit,git_repository,yor_trace
